# Generated by Django 4.0.4 on 2022-05-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='coordinates',
            field=models.CharField(default=(55.76, 37.64), max_length=50, verbose_name='Примерное местоположение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(upload_to='event_preview/'),
        ),
    ]
