# Generated by Django 4.0.4 on 2022-05-21 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_coordinates_alter_events_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='coordinates',
            new_name='place',
        ),
    ]
