# Generated by Django 4.0.4 on 2022-05-27 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_review_id_alter_review_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='event',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.events'),
            preserve_default=False,
        ),
    ]
