# Generated by Django 4.0.4 on 2022-05-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_featured_options_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, null=True),
        ),
    ]
